site:
  title: Ludic Art Guild Knowledge Base
  url: https://ludicartguild.github.io/knowledge-base
  start_page: knowledge-base::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: .

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
